package com.sergeikuchin.vinparser.dicts

internal val COUNTRIES: Map<String, String> =
    unpackCountries(
        mapOf(
            "A-AH" to "South Africa",
            "A-JN" to "Cote d'Ivoire",
            "B-AE" to "Angola",
            "B-FK" to "Kenya",
            "B-LR" to "Tanzania",
            "C-AE" to "Benin",
            "C-FK" to "Madagascar",
            "C-LR" to "Tunisia",
            "D-AE" to "Egypt",
            "D-FK" to "Morocco",
            "D-LR" to "Zambia",
            "E-AE" to "Ethiopia",
            "E-FK" to "Mozambique",
            "F-AE" to "Ghana",
            "F-FK" to "Nigeria",
            "J-A0" to "Japan",
            "K-AE" to "Sri Lanka",
            "K-FK" to "Israel",
            "K-LR" to "Korea (South),",
            "K-S0" to "Kazakhstan",
            "L-A0" to "China (Mainland),",
            "M-AE" to "India",
            "M-FK" to "Indonesia",
            "M-LR" to "Thailand",
            "M-S0" to "Myanmar",
            "N-AE" to "Iran",
            "N-FK" to "Pakistan",
            "N-LR" to "Turkey",
            "P-AE" to "Philippines",
            "P-FK" to "Singapore",
            "P-LR" to "Malaysia",
            "R-AE" to "United Arab Emirates",
            "R-FK" to "Taiwan, China",
            "R-LR" to "Vietnam",
            "R-S0" to "Saudi Arabia",
            "S-AM" to "United Kingdom",
            "S-NT" to "Germany/East Germany",
            "S-UZ" to "Poland",
            "S-14" to "Latvia",
            "T-AH" to "Switzerland",
            "T-JP" to "Czech Republic",
            "T-RV" to "Hungary",
            "T-W1" to "Portugal",
            "U-HM" to "Denmark",
            "U-NT" to "Ireland",
            "U-UZ" to "Romania",
            "U-57" to "Slovakia",
            "V-AE" to "Austria",
            "V-FR" to "France",
            "V-SW" to "Spain",
            "V-X2" to "Serbia",
            "V-35" to "Croatia",
            "V-60" to "Estonia",
            "W-A0" to "Germany/West Germany",
            "X-AE" to "Bulgaria",
            "X-FK" to "Greece",
            "X-LR" to "Netherlands",
            "X-SW" to "USSR/CIS",
            "X-X2" to "Luxembourg",
            "X-30" to "Russia",
            "Y-AE" to "Belgium",
            "Y-FK" to "Finland",
            "Y-LR" to "Malta",
            "Y-SW" to "Sweden",
            "Y-X2" to "Norway",
            "Y-35" to "Belarus",
            "Y-60" to "Ukraine",
            "Z-AR" to "Italy",
            "Z-X2" to "Slovenia",
            "Z-35" to "Lithuania",
            "1-A0" to "United States",
            "2-A0" to "Canada",
            "3-AW" to "Mexico",
            "3-X7" to "Costa Rica",
            "3-89" to "Cayman Islands",
            "4-A0" to "United States",
            "5-A0" to "United States",
            "6-A0" to "Australia",
            "7-A0" to "New Zealand",
            "8-AE" to "Argentina",
            "8-FK" to "Chile",
            "8-LR" to "Ecuador",
            "8-SW" to "Peru",
            "8-X2" to "Venezuela",
            "9-AE" to "Brazil",
            "9-FK" to "Colombia",
            "9-LR" to "Paraguay",
            "9-SW" to "Uruguay",
            "9-X2" to "Trinidad & Tobago",
            "9-39" to "Brazil",
        )
    )